# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/wojte/Desktop/FPGA-Vivado/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/ip/rgb2ycbcr_0/rgb2ycbcr_0.xci
# IP: The module: 'rgb2ycbcr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/wojte/Desktop/FPGA-Vivado/hdmi_vga_zybo/hdmi_vga_zybo.gen/sources_1/ip/rgb2ycbcr_0/src/add_1/add_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==add_1 || ORIG_REF_NAME==add_1} -quiet] -quiet

# IP: c:/Users/wojte/Desktop/FPGA-Vivado/hdmi_vga_zybo/hdmi_vga_zybo.gen/sources_1/ip/rgb2ycbcr_0/src/mult_gen_0/mult_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0} -quiet] -quiet

# IP: c:/Users/wojte/Desktop/FPGA-Vivado/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/ip/rgb2ycbcr_0/rgb2ycbcr_0.xci
# IP: The module: 'rgb2ycbcr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/wojte/Desktop/FPGA-Vivado/hdmi_vga_zybo/hdmi_vga_zybo.gen/sources_1/ip/rgb2ycbcr_0/src/add_1/add_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==add_1 || ORIG_REF_NAME==add_1} -quiet] -quiet

# IP: c:/Users/wojte/Desktop/FPGA-Vivado/hdmi_vga_zybo/hdmi_vga_zybo.gen/sources_1/ip/rgb2ycbcr_0/src/mult_gen_0/mult_gen_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0} -quiet] -quiet
