# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/wojte/Desktop/Systemy Rekonfigurowalne/lab2/lab2.srcs/sources_1/ip/mult_gen_5/mult_gen_5.xci
# IP: The module: 'mult_gen_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/wojte/Desktop/Systemy Rekonfigurowalne/lab2/lab2.gen/sources_1/ip/mult_gen_5/mult_gen_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_gen_5'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/wojte/Desktop/Systemy Rekonfigurowalne/lab2/lab2.srcs/sources_1/ip/mult_gen_5/mult_gen_5.xci
# IP: The module: 'mult_gen_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/wojte/Desktop/Systemy Rekonfigurowalne/lab2/lab2.gen/sources_1/ip/mult_gen_5/mult_gen_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_gen_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
