# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/wojte/Desktop/SystemyRekonfigurowalne/simulation_models/simulation_models.srcs/sources_1/ip/Block_LUT/Block_LUT.xci
# IP: The module: 'Block_LUT' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/wojte/Desktop/SystemyRekonfigurowalne/simulation_models/simulation_models.gen/sources_1/ip/Block_LUT/Block_LUT_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_LUT'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/wojte/Desktop/SystemyRekonfigurowalne/simulation_models/simulation_models.srcs/sources_1/ip/Block_LUT/Block_LUT.xci
# IP: The module: 'Block_LUT' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/wojte/Desktop/SystemyRekonfigurowalne/simulation_models/simulation_models.gen/sources_1/ip/Block_LUT/Block_LUT_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_LUT'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
